"use strict";

// Offline three-language layer. Mission data is translated structurally; DOM and Canvas
// strings use the same exact/phrase translator so runtime hints switch immediately.
(function createI18n(global){
  const KEY='spacegame-language-v1',SUPPORTED=['zh','en','ru'];
  const LABELS={zh:'中文',en:'English',ru:'Русский'};
  const EN={
    levels:[
      ['🚀 Mission 1 · Geostationary Satellite','Goal: place and release a satellite in the target orbit','Put a communications satellite into orbit, Captain. Release it inside the green zone for the best coverage.'],
      ['🪂 Mission 2 · Crewed Return','Goal: lower the orbit, deploy the parachute and land safely','Landing exam: bring the crew home gently. Land near the base, or they will have a very long walk.'],
      ['🛰️ Mission 3 · Station Rendezvous','Goal: deliver supplies safely to the station','The station needs supplies. Match its speed, approach slowly and do not shake the cargo apart.'],
      ['🌘 Mission 4 · Lunar Far-side Landing','Goal: deliver crew and equipment to the lunar far side','A research base is being built on the far side. Deliver its crew and equipment safely to the marked area.'],
      ['🌙 Mission 5 · Lunar Gravity Assist','Goal: use the Moon to escape through the green gate','Not enough fuel? Let the Moon help. Pass behind its direction of travel and use the gravity assist to escape Earth.'],
      ['⚖️ Mission 6 · Earth–Moon Balance Points','Goal: establish a relay in any balance zone','Build a long-term relay in any Earth–Moon balance zone. Enter a target area and reduce “Relative speed · target point”; little station-keeping fuel will be needed.'],
      ['☄️ Mission 7 · Asteroid Intercept','Goal: deflect the asteroid away from Earth and Moon','Danger: an asteroid is incoming. Land, anchor and use your engines—or strike it directly—to save Earth and the Moon.'],
      ['☀️ Mission 8 · Binary-star Ferry','Goal: deliver fuel to Twilight Station','Twilight Station needs fuel. Cross the moving gravity corridor, but keep the ship and cargo away from both stars.'],
      ['🕳️ Mission 9 · Black-hole Dive Burn','Goal: use the black hole and return to the rescue ring','Fuel is almost gone. Dive toward the black hole, burn at closest approach, then bring the crew back out.'],
      ['🌌 Final Mission · Three-body Rescue','Goal: rescue two drifting ships and escape the system','Two powerless ships are calling for help inside a chaotic three-star system. Reach either one first, transfer the crews, then escape together.']
    ],
    stages:[
      [
        ['① Launch into orbit','Turn right gradually after liftoff and complete one orbit','Hold thrust to lift off, then turn right slowly.','Keep accelerating until the ship no longer falls back.','Complete: the ship can orbit Earth safely.'],
        ['② Raise the far side','At periapsis, point along your motion and burn','Coast to the point closest to Earth.','Burn prograde to raise the opposite side.','Complete: apoapsis has entered the green target zone.'],
        ['③ Circularize the orbit','At apoapsis, burn prograde again','Coast to the point farthest from Earth.','Burn prograde until both ends enter the green band.','Complete: the whole orbit is stable in the target band.'],
        ['④ Release the satellite','When the button lights up, press Release Satellite','Wait for the orbit-stable prompt.','Release inside the green zone for an extra star.','Complete: the satellite is in synchronous orbit.']
      ],
      [
        ['① Deorbit burn','Turn opposite your motion and burn to begin descending','Point the nose opposite the flight direction.','Burn until predicted minimum altitude is below 250 u.','Complete: the return path enters the atmosphere.'],
        ['② Re-entry and parachute','Keep slowing; deploy below 520 u while descending','Use short retrograde burns.','Below 520 u while descending, press Deploy Parachute.','Complete: the parachute is open and speed is falling.'],
        ['③ Land safely','Point upward and tap thrust near the ground','Let the parachute remove most of the speed.','Align with local up and touch down gently.','Complete: Relative speed · ground is at most 7 u/s.']
      ],
      [
        ['① Reach station orbit','Turn right after liftoff and enter orbit','Lift off and turn right gradually.','Stabilize near the station altitude.','Complete: a prograde orbit near the station.'],
        ['② Catch the station','Stay slightly lower and approach from behind','Do not thrust at the station for a long time.','Inside 350 u, prepare to reduce “Relative speed · station”.','Complete: distance is below 350 u.'],
        ['③ Reduce Relative speed · station','Burn opposite Relative speed · station','Watch “Relative speed · station” in telemetry.','Use short burns: below 120 u and Relative speed · station below 22 u/s.','Complete: distance and Relative speed · station are safe.'],
        ['④ Dock','Approach slowly and dock when the button lights','Use tiny burns toward the green port.','Below 30 u and Relative speed · station below 8 u/s, press Dock.','Complete: supplies delivered safely.']
      ],
      [
        ['① Enter Earth orbit','Turn right after liftoff and establish a parking orbit','Lift off, then turn right gradually.','Complete one orbit and save fuel for the Moon.','Complete: safe Earth parking orbit.'],
        ['② Transfer to the Moon','At periapsis burn prograde to extend the orbit','Burn prograde at the point closest to Earth.','Aim where the Moon will be, not where it is now.','Complete: the ship is on a lunar transfer.'],
        ['③ Capture into lunar orbit','Turn around near the Moon and slow down','Point opposite Relative speed · Moon.','Use short burns until you will not fly past or crash.','Complete: safe lunar orbit.'],
        ['④ Land on the far side','Reach the green far side and descend slowly','Move toward the green far-side zone.','No parachute: land below 15 u/s using short burns.','Complete: crew and equipment are safely down.']
      ],
      [
        ['① Fly to the Moon','Follow the demo and send apoapsis toward the Moon','Launch and follow the demo turn.','Stop large corrections once apoapsis reaches lunar distance.','Complete: the ship is heading to the Moon.'],
        ['② Tune the flyby','Check predicted lunar periapsis: close, but above the surface','Coast and watch the impact/periapsis marker.','Use only tiny burns to correct the path.','Complete: the Moon will be passed safely.'],
        ['③ Take the gravity assist','Pass behind the Moon’s motion and mostly coast','Let lunar gravity bend the route.','As you leave, confirm Escape Speed is above 0.','Complete: the Moon has thrown the ship outward.'],
        ['④ Cross the escape gate','Keep moving outward through the large green ring','Coast toward the green ring.','Cross it with positive escape speed.','Complete: the ship will not fall back to Earth.']
      ],
      [
        ['① Inspect five relay zones','Choose any target and first enter Earth orbit','Turn right after launch and orbit Earth.','Tap the map for a global view of L1–L5.','Complete: targets located and orbit established.'],
        ['② Fly to any target','At periapsis burn prograde toward your chosen zone','Accelerate prograde at Earth periapsis.','Aim where the moving target will be.','Complete: within roughly 3000 u of a target.'],
        ['③ Match target speed','Turn around near the target and reduce Relative speed · target point','Watch distance and “Relative speed · target point”.','Burn opposite Relative speed · target point.','Complete: below 800 u and Relative speed · target point below 45 u/s.'],
        ['④ Establish the relay','Enter any target ring and hold position','Enter any one of the rings.','Reduce Relative speed · target point and hold steady.','Complete: the relay is stable in the target zone.']
      ],
      [
        ['① Intercept the asteroid','Use the red danger path and fly ahead of it','Tap the map after launch for the global view.','Aim ahead of the asteroid and intercept early.','Complete: inside the interception zone.'],
        ['② Make contact','Land slowly or strike it at high speed','Soft landing: contact below 22 u/s.','Impact: transfer the ship’s momentum directly.','Complete: the asteroid trajectory is changing.'],
        ['③ Anchor the ship','After landing, press Anchor & Flip','Anchor and flip so the engines point outward.','Left/right now adjust the thrust hinge.','Complete: anchored and ready to push.'],
        ['④ Push the danger path away','Adjust the jet angle until the prediction turns green','Watch whether the future path hits Earth or Moon.','Keep pushing until both bodies are safe.','Complete: safe path held for 2.5 seconds.']
      ],
      [
        ['① Leave Dawnworld','Launch from the blue planet toward the two stars','Thrust away from Dawnworld.','Avoid the red stellar heat zones.','Complete: ship and fuel cargo are airborne.'],
        ['② Cross the binary corridor','Aim ahead of the moving cyan corridor','Watch the corridor rotate with the stars.','Use short burns and pass through it.','Complete: the ship reaches the Twilight side.'],
        ['③ Capture around Twilight','Turn around near the blue-white star and slow down','Point opposite Relative speed · Twilight Star.','Retro-burn outside the heat zone to enter orbit.','Complete: captured by the Twilight star.'],
        ['④ Supply Twilight Station','Reduce “Relative speed · Twilight Station”, then approach and dock','Approach slowly from behind.','Below 36 u and Relative speed · Twilight Station below 9 u/s, execute docking.','Complete: fuel delivered to Twilight Station.']
      ],
      [
        ['① Dive toward the black hole','Tap thrust to start the world, then coast inward','The first tap only starts the world.','Coast inside the white ring.','Complete: inside the dive-burn zone.'],
        ['② Burn at closest approach','Inside the purple zone, point prograde and burn','Align with current motion.','Burn near 220–270 u; stop when escape energy turns green.','Complete: enough energy to escape.'],
        ['③ Bring the crew home','Keep flying outward through the green rescue ring','Confirm distance from the black hole is increasing.','Cross the green ring with positive escape energy.','Complete: ship and crew escaped the black hole.']
      ],
      [
        ['① Rescue either ship','A or B first; both are being pulled by the stars','Your first thrust starts all three stars and both ships.','Approach A or B; exact docking is not required.','Complete: the first crew is aboard.'],
        ['② Rescue the other ship','Reach it before a star does and reduce “Relative speed · distress ship”','The map keeps the remaining distress signal.','One loss still permits escape; losing both fails the mission.','Complete: all surviving crews are rescued.'],
        ['③ Escape with everyone','Choose an outward prediction region and cross the green boundary','Find a prediction corridor opening toward the outside of the system.','Cross the green ring while still moving outward.','Complete: all rescued crews escaped.']
      ]
    ],
    science:[
      ['Why does a synchronous satellite look stationary?','It is not still; it races around Earth once per rotation.',[['Conditions for synchrony','Its period must match Earth’s rotation, in the same direction and near the equator.'],['Two burns','A prograde burn at periapsis raises apoapsis; another at apoapsis raises periapsis and circularizes.'],['The green zone','Altitude controls synchrony; release longitude controls which region the satellite serves.']]],
      ['How does a spacecraft return from orbit?','Re-entry begins by lowering periapsis into the atmosphere.',[['Retrograde burn','Slowing down lowers the opposite side of the orbit until drag can take over.'],['Parachute','Deploy only when altitude and speed are safe: too early tears it, too late leaves no braking distance.'],['Landing speed','Safety uses “Relative speed · ground”, which subtracts the rotating ground’s motion.']]],
      ['Why not point straight at the station?','Orbital rendezvous is not like chasing a car.',[['Lower can be faster','A lower orbit has a shorter period, so it can catch a target from behind.'],['Match before approach','Nearby craft may still have a large velocity difference; reduce “Relative speed · station” before closing in.'],['Real docking','Radar, optical navigation and tiny attitude jets guide the final centimetres-per-second approach.']]],
      ['Why no parachute on the Moon?','The Moon has almost no atmosphere, so engines must control the descent.',[['Tidal locking','The Moon rotates once per orbit, keeping the same face toward Earth; the far side is not always dark.'],['Lunar capture','“Relative speed · Moon” must be reduced to enter orbit instead of flying past or crashing.'],['Powered landing','A late burn saves fuel but leaves little room for error.']]],
      ['How can the Moon accelerate a ship?','A gravity assist exchanges a tiny amount of energy with the moving Moon.',[['Which side','Passing behind the Moon’s motion usually accelerates the ship relative to Earth.'],['Distance matters','Closer means a stronger turn but greater collision risk.'],['True escape','Positive escape energy means speed remains even infinitely far away.']]],
      ['What are Earth–Moon balance zones?','Their scientific name is Lagrange points: forces cooperate in the rotating Earth–Moon frame.',[['Five locations','L1 lies between Earth and Moon; L2 beyond Moon; L3 opposite; L4 and L5 form triangles.'],['Gravity still exists','A satellite feels both bodies and must match the target’s motion.'],['Permanent?','L1–L3 need station-keeping; L4–L5 are more stable but still disturbed by other bodies.']]],
      ['How can a tiny push save Earth?','Conventional planetary defence changes velocity early; the Yamato Cannon is this mission’s high-energy special option.',[['Time magnifies changes','A tiny push years early becomes a huge miss distance.'],['Deflection and high-energy fragmentation','In reality, casually breaking an asteroid apart can leave a dangerous debris cloud, so impactors and steady thrust still aim to deflect the whole orbit. In this game, the Yamato Cannon vaporises and rapidly disperses the fragments, so a direct hit removes the threat.'],['Gravity and spin','Even a small asteroid has gravity and rotational inertia.']]],
      ['Why is there a corridor between two stars?','Both stars move and both pull the ship.',[['Common barycentre','The stars orbit their shared centre of mass; the launch planet carries orbital velocity too.'],['Moving corridor','A narrow route through the rotating gravity field moves with the stars.'],['Slow down after crossing','Arrival is not capture; remove relative energy or the station will be passed at high speed.']]],
      ['Time and efficient burns near a black hole','The mission combines gravitational time dilation, redshift and a periapsis burn.',[['Slow motion from afar','Signals become redder and farther apart near the horizon, while onboard time feels normal.'],['Why dive','Burning where gravity has made the ship fastest adds the most orbital energy—the Oberth effect.'],['Beyond the horizon','The horizon is not a surface, but no signal can return after crossing it.']]],
      ['Why is every three-body route different?','Deterministic gravity can amplify tiny differences into entirely different paths.',[['Chaos is not randomness','Minute changes in starting position or speed alter the long-term route.'],['Prediction corridor','The translucent region is bounded by the leftmost and rightmost corrections; it widens as the forecasts diverge.'],['Distress ships','Approach transfers crews without exact docking; then find a diverging route out.']]]
    ]
  };
  const RU={
    levels:[
      ['🚀 Миссия 1 · Геостационарный спутник','Цель: вывести спутник на нужную орбиту и отделить его','Доставьте спутник связи на орбиту. Отделите его в зелёной зоне для лучшего покрытия.'],
      ['🪂 Миссия 2 · Возвращение экипажа','Цель: снизить орбиту, раскрыть парашют и мягко сесть','Посадочный экзамен: верните экипаж домой и постарайтесь сесть недалеко от базы.'],
      ['🛰️ Миссия 3 · Стыковка со станцией','Цель: безопасно доставить груз на станцию','Станции нужны припасы. Сравняйте скорость, подходите медленно и берегите груз.'],
      ['🌘 Миссия 4 · Посадка на обратной стороне Луны','Цель: доставить людей и оборудование на обратную сторону','На обратной стороне строят научную базу. Доставьте экипаж и оборудование в отмеченную область.'],
      ['🌙 Миссия 5 · Лунный гравитационный манёвр','Цель: разогнаться у Луны и выйти через зелёные ворота','Топлива мало? Пройдите позади Луны по направлению её движения и используйте её притяжение для ухода от Земли.'],
      ['⚖️ Миссия 6 · Точки равновесия Земля–Луна','Цель: разместить ретранслятор в любой зоне равновесия','Создайте узел связи в любой зоне равновесия. Войдите в цель и уменьшите «Относительная скорость · целевая точка».'],
      ['☄️ Миссия 7 · Перехват астероида','Цель: увести астероид от Земли и Луны','Опасный астероид приближается. Сядьте на него и толкайте двигателями — либо измените путь прямым ударом.'],
      ['☀️ Миссия 8 · Переправа в двойной системе','Цель: доставить топливо на станцию «Сумерки»','Пройдите через движущийся гравитационный коридор и не подпускайте корабль и груз слишком близко к звёздам.'],
      ['🕳️ Миссия 9 · Импульс у чёрной дыры','Цель: разогнаться у чёрной дыры и вернуться к спасательному кольцу','Топливо почти кончилось. Нырните к чёрной дыре, дайте импульс в перицентре и выведите экипаж обратно.'],
      ['🌌 Финал · Спасение в системе трёх тел','Цель: спасти два корабля и покинуть систему','В хаотичной тройной системе терпят бедствие два корабля. Сначала спасите любой, затем второй и уходите вместе.']
    ],
    stages:[
      [
        ['① Выход на орбиту','После старта плавно поверните вправо и сделайте виток','Держите тягу и медленно поворачивайте вправо.','Разгоняйтесь, пока корабль не перестанет падать.','Готово: корабль безопасно обращается вокруг Земли.'],
        ['② Поднять дальнюю точку','В перицентре направьте нос по скорости и дайте тягу','Долетите до ближайшей к Земле точки.','Разгонитесь по ходу полёта, поднимая противоположную сторону.','Готово: апоцентр вошёл в зелёную целевую зону.'],
        ['③ Сделать орбиту круглой','В апоцентре снова разгонитесь по ходу полёта','Долетите до самой дальней точки.','Дайте тягу, пока обе стороны не войдут в зелёную полосу.','Готово: вся орбита находится в целевой полосе.'],
        ['④ Отделить спутник','Когда кнопка загорится, нажмите «Отделить спутник»','Дождитесь сообщения об устойчивой орбите.','Отделение в зелёной зоне даёт дополнительную звезду.','Готово: спутник на синхронной орбите.']
      ],
      [
        ['① Торможение для схода','Развернитесь против скорости и начните снижение','Направьте нос против движения.','Тормозите до расчётной высоты менее 250 u.','Готово: траектория вошла в атмосферу.'],
        ['② Вход и парашют','Продолжайте тормозить; раскройте ниже 520 u','Используйте короткие тормозные импульсы.','Ниже 520 u при снижении нажмите «Раскрыть парашют».','Готово: парашют раскрыт, скорость падает.'],
        ['③ Мягкая посадка','Держите нос вверх и слегка включайте тягу у земли','Пусть парашют погасит основную скорость.','Выровняйтесь по местной вертикали и мягко коснитесь земли.','Готово: Относительная скорость · поверхность не выше 7 u/s.']
      ],
      [
        ['① Орбита станции','После старта поверните вправо и выйдите на орбиту','Взлетите и постепенно поворачивайте вправо.','Стабилизируйтесь на высоте станции.','Готово: попутная орбита рядом со станцией.'],
        ['② Догнать станцию','Идите немного ниже и догоняйте сзади','Не разгоняйтесь долго прямо на станцию.','Ближе 350 u уменьшите «Относительная скорость · станция».','Готово: расстояние менее 350 u.'],
        ['③ Уменьшить Относительная скорость · станция','Тормозите против Относительная скорость · станция','Следите за «Относительная скорость · станция».','Добейтесь 120 u и Относительная скорость · станция ниже 22 u/s.','Готово: расстояние и Относительная скорость · станция безопасны.'],
        ['④ Стыковка','Подойдите медленно и стыкуйтесь по сигналу кнопки','Коротко подталкивайте корабль к зелёному порту.','При 30 u и Относительная скорость · станция ниже 8 u/s нажмите «Стыковка».','Готово: груз доставлен.']
      ],
      [
        ['① Земная парковочная орбита','После старта поверните вправо и стабилизируйтесь','Взлетите и постепенно поверните вправо.','Сделайте виток и берегите топливо для Луны.','Готово: безопасная парковочная орбита.'],
        ['② Перелёт к Луне','В перицентре разгонитесь и вытяните орбиту к Луне','Разгонитесь по ходу движения у Земли.','Цельтесь туда, где Луна будет позже.','Готово: корабль на трассе к Луне.'],
        ['③ Захват Луной','У Луны развернитесь и затормозите','Направьтесь против Относительная скорость · Луна.','Тормозите коротко, чтобы не пролететь и не столкнуться.','Готово: безопасная лунная орбита.'],
        ['④ Посадка на обратной стороне','Достигните зелёной зоны и снижайтесь медленно','Перейдите к зелёной области обратной стороны.','Парашюта нет: посадка должна быть медленнее 15 u/s.','Готово: люди и оборудование доставлены.']
      ],
      [
        ['① Полёт к Луне','Следуйте за демонстрацией и поднимите апоцентр к Луне','Стартуйте и повторяйте поворот демонстратора.','Когда апоцентр достигнет Луны, прекратите большие коррекции.','Готово: корабль летит к Луне.'],
        ['② Настроить пролёт','Проверьте перицентр у Луны: близко, но над поверхностью','Летите по инерции и следите за меткой столкновения.','Используйте только малые коррекции.','Готово: безопасный близкий пролёт.'],
        ['③ Получить разгон','Пройдите позади движения Луны почти без тяги','Позвольте Луне искривить траекторию.','На выходе скорость убегания должна быть выше 0.','Готово: Луна отбросила корабль наружу.'],
        ['④ Выйти через ворота','Продолжайте наружу через большое зелёное кольцо','Летите по инерции к зелёному кольцу.','Пересеките его с положительной скоростью убегания.','Готово: корабль не вернётся к Земле.']
      ],
      [
        ['① Осмотреть пять зон','Выберите любую цель и сначала выйдите на орбиту','После старта поверните вправо и облетите Землю.','Нажмите карту и найдите L1–L5.','Готово: цели видны, орбита создана.'],
        ['② Лететь к любой цели','В перицентре разгонитесь к выбранной зоне','Разгонитесь по ходу движения у Земли.','Цель движется — летите к её будущему месту.','Готово: до цели около 3000 u.'],
        ['③ Сравнять скорость','У цели развернитесь и уменьшите Относительная скорость · целевая точка','Следите за расстоянием и «Относительная скорость · целевая точка».','Тормозите против Относительная скорость · целевая точка.','Готово: менее 800 u и Относительная скорость · целевая точка ниже 45 u/s.'],
        ['④ Развернуть ретранслятор','Войдите в любое кольцо и удерживайтесь','Войдите в одно из целевых колец.','Уменьшите Относительная скорость · целевая точка и удерживайте положение.','Готово: ретранслятор устойчив.']
      ],
      [
        ['① Перехватить астероид','По красной траектории летите ему навстречу','После старта откройте общий вид карты.','Цельтесь впереди астероида и перехватите его заранее.','Готово: вы в зоне перехвата.'],
        ['② Коснуться астероида','Мягко сядьте или ударьте на большой скорости','Мягкая посадка: скорость ниже 22 u/s.','Удар: передайте астероиду импульс корабля.','Готово: траектория астероида меняется.'],
        ['③ Закрепиться','После посадки нажмите «Якорь и переворот»','Закрепитесь двигателями наружу.','Лево/право теперь меняют угол шарнира.','Готово: корабль закреплён.'],
        ['④ Увести опасную траекторию','Меняйте угол тяги, пока прогноз не станет зелёным','Проверьте будущие встречи с Землёй и Луной.','Толкайте, пока обе цели не будут в безопасности.','Готово: безопасная траектория держится 2,5 с.']
      ],
      [
        ['① Покинуть планету Рассвета','Стартуйте к проходу между звёздами','Включите тягу и покиньте синюю планету.','Не входите в красные горячие зоны.','Готово: корабль и груз взлетели.'],
        ['② Пройти коридор','Цельтесь впереди движущегося голубого прохода','Следите за вращением прохода вместе со звёздами.','Короткими импульсами пройдите через него.','Готово: вы на стороне Сумерек.'],
        ['③ Захват у Сумерек','У бело-голубой звезды развернитесь и затормозите','Направьтесь против Относительная скорость · звезда Сумерек.','Тормозите вне горячей зоны и войдите на орбиту.','Готово: звезда Сумерек захватила корабль.'],
        ['④ Снабдить станцию','Уменьшите «Относительная скорость · станция Сумерек», затем подойдите и состыкуйтесь','Медленно подойдите сзади.','При 36 u и Относительная скорость · станция Сумерек ниже 9 u/s выполните стыковку.','Готово: топливо доставлено.']
      ],
      [
        ['① Нырнуть к чёрной дыре','Коснитесь тяги для запуска мира, затем летите внутрь','Первое нажатие только запускает мир.','Летите по инерции внутрь белого кольца.','Готово: вы в зоне эффективного импульса.'],
        ['② Импульс в перицентре','В фиолетовой зоне направьтесь по скорости и разгонитесь','Совместите нос с направлением движения.','Дайте тягу на 220–270 u и остановитесь при зелёной энергии.','Готово: энергии достаточно для ухода.'],
        ['③ Вернуть экипаж','Летите наружу через зелёное спасательное кольцо','Убедитесь, что расстояние до дыры растёт.','Пересеките кольцо с положительной энергией ухода.','Готово: корабль и экипаж спасены.']
      ],
      [
        ['① Спасти любой корабль','Сначала A или B — оба притягиваются звёздами','Первое включение тяги запускает все тела.','Подойдите к A или B; точная стыковка не нужна.','Готово: первый экипаж на борту.'],
        ['② Спасти второй','Успейте раньше звезды и снизьте «Относительная скорость · аварийный корабль»','На карте остаётся второй сигнал бедствия.','Потеря одного допустима; потеря обоих завершает миссию.','Готово: все выжившие спасены.'],
        ['③ Уйти вместе','Выберите расширяющуюся наружу область прогноза и выйдите за зелёную границу','Найдите коридор прогноза, раскрывающийся наружу системы.','Пересеките кольцо, продолжая удаляться.','Готово: спасённые экипажи покинули систему.']
      ]
    ],
    science:[
      ['Почему синхронный спутник кажется неподвижным?','Он не стоит на месте, а делает оборот за время вращения Земли.',[['Условия синхронности','Период равен земным суткам, направление совпадает с вращением, орбита проходит у экватора.'],['Два импульса','Разгон в перицентре поднимает апоцентр, а разгон в апоцентре поднимает перицентр.'],['Зелёная зона','Высота задаёт синхронность, а долгота отделения — обслуживаемый район.']]],
      ['Как вернуться с орбиты?','Сначала нужно опустить перицентр в атмосферу.',[['Тормозной импульс','Уменьшение скорости опускает противоположную сторону орбиты, затем работает сопротивление воздуха.'],['Парашют','Слишком рано — перегрузка и разрыв, слишком поздно — не хватит пути для торможения.'],['Скорость посадки','Используется «Относительная скорость · поверхность» с учётом вращения Земли.']]],
      ['Почему нельзя просто лететь прямо к станции?','Орбитальное сближение не похоже на погоню по дороге.',[['Ниже — быстрее','У низкой орбиты короче период, поэтому она помогает догнать цель сзади.'],['Сначала сравнять скорость','Даже рядом скорости могут различаться; снизьте «Относительная скорость · станция» до сближения.'],['Настоящая стыковка','Радар, оптика и малые двигатели ведут последние метры со скоростью сантиметров в секунду.']]],
      ['Почему на Луне нет парашюта?','У Луны почти нет атмосферы, поэтому тормозят только двигатели.',[['Приливный захват','Луна вращается один раз за оборот и всегда обращена к Земле одной стороной.'],['Лунный захват','Снизьте «Относительная скорость · Луна», иначе корабль пролетит мимо или столкнётся.'],['Активная посадка','Позднее торможение экономит топливо, но почти не оставляет запаса на ошибку.']]],
      ['Как Луна разгоняет корабль?','Гравитационный манёвр обменивается энергией с движущейся Луной.',[['С какой стороны','Пролёт позади движения Луны обычно ускоряет корабль относительно Земли.'],['Расстояние','Ближе — сильнее поворот, но выше риск столкновения.'],['Настоящий уход','Положительная энергия означает ненулевую скорость даже на бесконечности.']]],
      ['Что такое зоны равновесия Земля–Луна?','Научное название — точки Лагранжа в совместно вращающейся системе.',[['Пять мест','L1 между телами, L2 за Луной, L3 напротив, L4 и L5 образуют треугольники.'],['Притяжение не исчезает','Спутник ощущает оба тела и должен совпадать со скоростью цели.'],['Навсегда?','L1–L3 требуют коррекций; L4–L5 устойчивее, но испытывают возмущения.']]],
      ['Как малый толчок спасает Землю?','Обычная защита планеты заранее меняет скорость; пушка «Ямато» — особый высокоэнергетический вариант этой миссии.',[['Время усиливает эффект','Малый импульс за годы превращается в огромный промах.'],['Отклонение и высокоэнергетическое дробление','В реальности простое разрушение астероида может оставить опасное облако обломков, поэтому ударные аппараты и постоянная тяга отклоняют всю орбиту. В игре пушка «Ямато» испаряет и быстро рассеивает обломки, поэтому прямое попадание устраняет угрозу.'],['Гравитация и вращение','Даже небольшой астероид имеет притяжение и момент инерции.']]],
      ['Почему между звёздами есть коридор?','Обе звезды движутся и одновременно притягивают корабль.',[['Общий барицентр','Звёзды обращаются вокруг общего центра масс.'],['Движущийся проход','Узкий путь в поле тяготения вращается вместе со звёздами.'],['После прохода тормозите','Прибытие ещё не захват: уберите лишнюю энергию перед станцией.']]],
      ['Время и импульс у чёрной дыры','Здесь видны замедление времени, красное смещение и эффект Оберта.',[['Замедление издали','Сигналы у горизонта краснеют и приходят всё реже, но собственное время экипажа обычно.'],['Зачем нырять','Импульс в точке максимальной скорости сильнее увеличивает энергию орбиты.'],['За горизонтом','Горизонт не поверхность, но после пересечения сигнал наружу не вернётся.']]],
      ['Почему маршрут трёх тел каждый раз иной?','Точные законы тяготения быстро усиливают малейшие различия.',[['Хаос не случайность','Крошечная разница начальных условий меняет дальнюю траекторию.'],['Коридор прогноза','Полупрозрачная область ограничена крайними левым и правым прогнозами и расширяется по мере их расхождения.'],['Корабли бедствия','Достаточно подойти для передачи экипажа, затем найти расходящийся путь наружу.']]]
    ]
  };
  const ACH_TRANSLATIONS={
    en:[
      ['Ignition Permit','Press thrust for the first time.','Every journey begins with heat and paperwork.'],['Falling Sideways','Create a closed, surface-safe Earth orbit.','Congratulations: you learned to miss the ground forever.'],['Stationary Courier','Finish Mission 1 in synchronous orbit.','Standing still requires moving extremely fast.'],['Trust the Fabric','Deploy the parachute yourself in Mission 2.','A mature astronaut knows when to trust a large cloth.'],['Do Not Slam the Door','Land the crew safely in Mission 2.','The hardest part of coming home is not making a new crater.'],['Orbital Handshake','Dock with a station in Mission 3 or 8.','The most expensive gentle tap in the universe.'],['Far-side Footprint','Land on the lunar far side in Mission 4.','No signal, but at least nobody steals the view.'],['Borrowed Momentum','Use the Moon to escape in Mission 5.','The Moon did not push you; it politely lent you speed.'],['Gravity Balancer','Hold at any Earth–Moon balance point.','You parked where even gravity cannot decide.'],['Asteroid Negotiator','Deflect the asteroid away from Earth and Moon.','World saved. The paint-damage invoice is on its way.'],['Two-sun Commuter','Cross the binary corridor and dock.','One sun was not enough for the commute.'],['Reply from the Abyss','Burn near the black hole and escape.','You beat the hole; mission control’s clock aged first.'],['Chaos Rescue Captain','Rescue both ships and escape the three-body system.','Three suns had no plan. Somehow you did.'],['Five-G Club','Survive at least 5G without damage.','Your face stayed in the seat; your soul barely followed.'],['Challenge Ace','Earn three stars in any challenge mission.','Infinite fuel was the lesson. You skipped it.'],['Voyager of Ten Worlds','Complete all ten missions.','You can now explain every problem with orbital mechanics.'],
      ['Fly Without Answers','Finish a challenge with trajectory prediction off for the whole flight.','The prediction line took leave. Newton was called in to navigate.'],['Six Burns or Fewer','Finish any challenge using no more than six burn segments.','The engine spoke rarely, but every sentence changed the orbit.'],['Silent Drifter','Coast continuously without power for at least 30 seconds and finish a challenge.','The longest operation was doing absolutely nothing with conviction.'],['Park Somewhere Else','Finish Mission 6 from at least two different Lagrange points.','Five parking spaces exist; you refused the monthly pass.'],['Gentle Persuasion','Soft-land on the asteroid, then finish planetary defence with sustained thrust.','No impact, no explosion—just a negotiation with excellent thrust.'],['Ship as Hammer','Finish Mission 7 using the kinetic-impact route.','The brief said “change the orbit”; you chose the strongest punctuation.'],['No Reload Pilot','Finish any challenge without stage rewind.','There was one timeline because you gave the universe no second thoughts.'],['Prisoner 7251 Tag','Destroy a friendly station with Hyperion’s Yamato Cannon.','He says a cat spilled coffee and shorted the firing button. Even the cat shakes its head.'],['Inertia Has Opinions','Spend at least 30 seconds in pure-inertia attitude and finish a challenge.','The ship will not turn for you. It quietly respects your decision.']
    ],
    ru:[
      ['Допуск к зажиганию','Впервые нажмите тягу.','Любой путь начинается с жара и разрешения.'],['Падение вбок','Создайте замкнутую безопасную орбиту Земли.','Поздравляем: вы научились всё время промахиваться мимо земли.'],['Неподвижный курьер','Завершите первую миссию на синхронной орбите.','Чтобы стоять на месте, надо лететь очень быстро.'],['Доверие к ткани','Самостоятельно раскройте парашют во второй миссии.','Зрелый космонавт знает, когда довериться большому куску ткани.'],['Не хлопай дверью','Безопасно посадите экипаж во второй миссии.','Главное при возвращении — не сделать новый кратер у дома.'],['Орбитальное рукопожатие','Состыкуйтесь со станцией в миссии 3 или 8.','Самое дорогое лёгкое касание во Вселенной.'],['След на обратной стороне','Сядьте на обратной стороне Луны.','Связи нет, зато вид никто не отнимет.'],['Скорость взаймы','Используйте Луну для ухода в миссии 5.','Луна не толкала вас — она вежливо одолжила скорость.'],['Укротитель равновесия','Остановитесь у любой точки равновесия.','Вы припарковались там, где даже гравитация сомневается.'],['Переговорщик с астероидом','Уведите астероид от Земли и Луны.','Мир спасён. Счёт за царапины уже отправлен.'],['Пассажир двух солнц','Пройдите двойную систему и состыкуйтесь.','Одного солнца для сложной дороги было мало.'],['Ответ из бездны','Дайте импульс у чёрной дыры и уйдите.','Вы победили дыру, но часы центра постарели первыми.'],['Капитан хаотического спасения','Спасите оба корабля и покиньте систему.','Три солнца не знали план. Вы почему-то знали.'],['Клуб пяти G','Перенесите 5G без потери корабля и экипажа.','Лицо осталось в кресле, душа едва догнала.'],['Ас испытаний','Получите три звезды в любом испытании.','Бесконечное топливо было учебным. Вы не слушали.'],['Путешественник десяти миров','Завершите все десять миссий.','Теперь любую проблему можно объяснить орбитальной механикой.'],
      ['Лететь без ответов','Завершите испытание с выключенным прогнозом траектории на всём полёте.','Линия прогноза ушла в отпуск. Для навигации вызвали Ньютона.'],['Не больше шести импульсов','Завершите любое испытание не более чем за шесть включений тяги.','Двигатель говорил редко, но каждая фраза меняла орбиту.'],['Тихий дрейф','Летите без тяги не менее 30 секунд подряд и завершите испытание.','Самым длинным действием было решительно ничего не делать.'],['Припарковаться в другом месте','Завершите миссию 6 как минимум у двух разных точек Лагранжа.','Есть пять мест, но вы отказались от постоянного абонемента.'],['Мягкое убеждение','Мягко сядьте на астероид и завершите защиту длительной тягой.','Без удара и взрыва — только переговоры с отличной тягой.'],['Корабль-молот','Завершите миссию 7 по маршруту кинетического удара.','В задании было «изменить орбиту», и вы выбрали самый сильный знак препинания.'],['Пилот без перезагрузки','Завершите испытание без отката этапа.','Линия времени одна: Вселенной не дали передумать.'],['Жетон заключённого 7251','Уничтожьте дружественную станцию пушкой «Ямато» корабля «Гиперион».','Он говорит, что кот пролил кофе и замкнул кнопку огня. Даже кот качает головой.'],['У инерции своё мнение','Проведите 30 секунд в режиме чистой инерции и завершите испытание.','Корабль не поворачивает за вас. Он уважает ваше решение.']
    ]
  };

  const UI_ROWS=[
    ['🌐 中文','🌐 English','🌐 Русский'],
    ['飞行已暂停','Flight paused','Полёт приостановлен'],['常用设置都收在这里，飞行画面只保留必要操作。','Common settings are here; only essential controls stay on screen.','Основные настройки собраны здесь, на экране остались только нужные кнопки.'],
    ['▶ 继续飞行','▶ Resume flight','▶ Продолжить'],['↻ 整关重来','↻ Restart mission','↻ Начать миссию заново'],['⌂ 回主菜单','⌂ Main menu','⌂ Главное меню'],['轨迹预测','Trajectory prediction','Прогноз траектории'],['色觉辅助','Color vision assist','Помощь при нарушении цветовосприятия'],['色觉辅助已开启｜危险区叉号、目标区圆点','Color vision assist enabled · danger zones use X marks, targets use dots','Помощь цветовосприятия включена · опасные зоны отмечены крестами, цели — точками'],['色觉辅助已关闭','Color vision assist disabled','Помощь цветовосприятия выключена'],['小地图模式','Radar mode','Режим карты'],['姿态模式','Attitude mode','Режим ориентации'],['表盘模式','Dial mode','Режим прибора'],['任务提示','Mission guidance','Подсказки'],['📋 任务简报','📋 Mission briefing','📋 Брифинг'],['📚 航天科普','📚 Space science','📚 Космическая наука'],['🎵 音乐：开启','🎵 Music: On','🎵 Музыка: вкл.'],['🔇 音乐：关闭','🔇 Music: Off','🔇 Музыка: выкл.'],['🔇 此浏览器不支持音乐','🔇 Music is not supported by this browser','🔇 Этот браузер не поддерживает музыку'],['音乐音量','Music volume','Громкость музыки'],['🎵 音乐已开启','🎵 Music enabled','🎵 Музыка включена'],['🔇 音乐已关闭','🔇 Music disabled','🔇 Музыка выключена'],['📋 复制手机性能报告','📋 Copy performance report','📋 Копировать отчёт'],['⭐ 本关星级条件','⭐ Star requirements','⭐ Условия звёзд'],
    ['⚙️ 游戏设置','⚙️ Game settings','⚙️ Настройки игры'],['关闭游戏设置','Close game settings','Закрыть настройки игры'],['声音、语言、显示和测试选项集中在这里；飞船、勋章与升级仍在任务目录中。','Sound, language, display and testing options are collected here; ships, medals and upgrades remain in the mission directory.','Звук, язык, экран и тестовые параметры собраны здесь; корабли, медали и улучшения остаются в каталоге миссий.'],['🔊 声音','🔊 Sound','🔊 Звук'],['音效音量','Sound-effects volume','Громкость эффектов'],['🌐 常规与辅助','🌐 General and assistance','🌐 Общие и вспомогательные'],['🧪 测试','🧪 Testing','🧪 Тестирование'],
    ['音乐等待首次点击后播放。','Music will start after the first click.','Музыка начнётся после первого нажатия.'],['音乐准备中。','Music is getting ready.','Музыка готовится.'],['正在播放：','Now playing: ','Сейчас играет: '],['音乐文件加载失败，请重新发布 dist/music。','Music files failed to load. Republish dist/music.','Не удалось загрузить музыку. Опубликуйте dist/music заново.'],['浏览器阻止了音乐，请再次点击页面。','The browser blocked music. Click the page again.','Браузер заблокировал музыку. Нажмите на страницу ещё раз.'],['此浏览器不支持背景音乐。','This browser does not support background music.','Этот браузер не поддерживает фоновую музыку.'],['音乐已关闭。','Music is turned off.','Музыка выключена.'],
    ['🌌 宇宙种子：随机','🌌 Universe seed: Random','🌌 Семя вселенной: случайное'],['🌌 宇宙种子：固定本局','🌌 Universe seed: Lock current','🌌 Семя вселенной: зафиксировано'],['🌌 练习模式：固定本局宇宙种子（关闭）','🌌 Practice: lock current universe seed (Off)','🌌 Тренировка: зафиксировать текущее семя (выкл.)'],['🌌 练习模式：固定本局宇宙种子（开启）','🌌 Practice: lock current universe seed (On)','🌌 Тренировка: зафиксировать текущее семя (вкл.)'],['🎲 已切换随机种子｜下次整关重来生效','🎲 Random seed enabled | Applies on the next full restart','🎲 Случайное семя включено | Применится при полном перезапуске'],['长按复制宇宙种子','Press and hold to copy the universe seed','Удерживайте, чтобы скопировать семя вселенной'],['教学：无限燃料和辅助。完成得 1 星。','Training: unlimited fuel and assists. Complete for 1 star.','Обучение: топливо и помощь без ограничений. За выполнение — 1 звезда.'],['挑战：有限燃料。按下方条件得星；切换会重开本关。','Challenge: limited fuel. Earn stars from the conditions below; switching restarts the mission.','Испытание: топливо ограничено. Выполните условия ниже для звёзд; смена режима перезапустит миссию.'],['固定练习：整关重来保持当前宇宙；星级正常结算，分数不计入最高分。','Fixed practice: a full restart keeps this universe; stars count, but the score does not update your best.','Фиксированная тренировка: перезапуск сохраняет эту вселенную; звёзды засчитываются, но рекорд не обновляется.'],['随机模式：下次整关重来生成新宇宙；成绩可计入最高分。','Random mode: the next full restart creates a new universe; the result can update your best score.','Случайный режим: полный перезапуск создаёт новую вселенную; результат может обновить рекорд.'],['当前种子：','Current seed: ','Текущее семя: '],['固定种子练习：整关重来保持同一宇宙；本局星级正常结算，分数不计入最高分。','Fixed-seed practice keeps the same universe on restart; stars count, but the score does not update your best.','Тренировка с фиксированным семенем сохраняет ту же вселенную; звёзды засчитываются, но рекорд не обновляется.'],['随机种子模式：整关重来会扰动三颗恒星的初始条件，本局成绩可计入最高分。','Random-seed mode perturbs the three stars on restart; this result can update your best score.','Режим случайного семени меняет начальные условия трёх звёзд; результат может обновить рекорд.'],['本局练习得分 ','Practice score ','Счёт тренировки '],
    ['⌨️ 电脑按键','⌨️ Keyboard controls','⌨️ Клавиши'],['推进','Thrust','Тяга'],['转向','Turn','Поворот'],['任务动作','Mission action','Действие'],['视角','Camera','Камера'],['地图','Map','Карта'],['姿态','Attitude','Ориентация'],['表盘','Dial','Прибор'],['轨迹','Path','Траектория'],['教学/挑战','Training/Challenge','Обучение/Испытание'],['音效','Sound','Звук'],['阶段回退','Stage rewind','Откат этапа'],['整关重来','Restart mission','Начать заново'],['暂停','Pause','Пауза'],['继续','Resume','Продолжить'],['跟随','Follow','Слежение'],['静止','Fixed','Фиксировано'],['倍速','Time warp','Ускорение'],['左转','Turn left','Влево'],['右转','Turn right','Вправо'],
    ['任务简报','Mission briefing','Брифинг миссии'],['关键目标','Key objective','Главная цель'],['当前操作','What to do now','Что делать сейчас'],['任务步骤','Mission steps','Этапы миссии'],['当前步骤','Current step','Текущий этап'],['后续步骤','Later step','Следующий этап'],['完成当前步骤后解锁','Unlocks after the current step','Откроется после текущего этапа'],['已完成','Complete','Завершено'],['⭐ 模式与星级','⭐ Mode and stars','⭐ Режим и звёзды'],['教学 · 无限燃料','Training · Unlimited fuel','Обучение · Топливо без лимита'],['挑战 · 有限燃料','Challenge · Limited fuel','Испытание · Топливо ограничено'],['u / u/s 是本游戏的缩比单位。','u / u/s are scaled game units.','u / u/s — условные единицы игры.'],['📚 本关科普','📚 Mission science','📚 Наука миссии'],['关闭新手指引','Hide guidance','Скрыть подсказки'],['开启新手指引','Show guidance','Показать подсказки'],['继续飞行','Continue flight','Продолжить полёт'],['航天知识库','Spaceflight library','Библиотека космонавтики'],['返回暂停菜单','Back to pause menu','Вернуться в меню паузы'],['返回任务简报','Back to briefing','Вернуться к брифингу'],
    ['穿过救援门并逃离黑洞：★','Escape through the rescue gate: ★','Пройдите спасательные ворота и покиньте чёрную дыру: ★'],['在半径 270 u 内完成深渊点火：+★','Perform the dive burn within 270 u: +★','Выполните импульс в пределах 270 u: +★'],['挑战燃料剩余至少 5%：+★','Challenge fuel remaining at least 5%: +★','Остаток топлива в испытании не менее 5%: +★'],['在半径 270 u 内完成深渊点火','Perform the dive burn within 270 u','Выполните импульс в пределах 270 u'],['燃料剩余至少 5%','Fuel remaining at least 5%','Остаток топлива не менее 5%'],
    ['概念卡片：','Concept cards: ','Карточки понятий: '],['概念卡片：开启','Concept cards: On','Карточки понятий: вкл.'],['概念卡片：关闭','Concept cards: Off','Карточки понятий: выкл.'],['🪐 回看轨道概念','🪐 Review orbital concept','🪐 Повторить понятие орбиты'],['概念卡片已开启','Concept cards enabled','Карточки понятий включены'],['概念卡片已关闭','Concept cards disabled','Карточки понятий выключены'],
    ['轨道概念','Orbital concept','Орбитальное понятие'],['在最远处点火','Burn at apoapsis','Импульс в апоцентре'],['⏸ 飞行已暂停','⏸ Flight paused','⏸ Полёт приостановлен'],['在轨道最远处点火并抬高另一端的示意图','Diagram of a burn at apoapsis raising the other side of the orbit','Схема импульса в апоцентре, поднимающего другую сторону орбиты'],['点火处','Burn point','Точка импульса'],['另一端抬高','Other side rises','Другой край выше'],['在离地球最远的位置朝飞行方向点火，会抬高轨道另一端。','At the point farthest from Earth, burn prograde to raise the other side of the orbit.','В самой дальней от Земли точке включите тягу по ходу движения — противоположная сторона орбиты поднимется.'],['先滑行到最远处','Coast to the farthest point','Сначала долетите до дальней точки'],['机头朝飞行方向','Point the nose along your direction of travel','Направьте нос по ходу движения'],['短促点火，观察青色新轨道','Use a short burn and watch the new cyan orbit','Дайте короткий импульс и следите за новой голубой орбитой'],['跳过并继续','Skip and continue','Пропустить и продолжить'],['明白了，继续飞行','Got it — continue','Понятно, продолжить'],
    ['在近地点顺向点火','Burn prograde at periapsis','Импульс по ходу движения в перицентре'],['继续飞行 · 3 秒后自动收起','Flight continues · closes in 3 seconds','Полёт продолжается · закроется через 3 секунды'],['近地点顺向点火抬高轨道远端的示意图','Diagram of a prograde periapsis burn raising the far side of the orbit','Схема подъёма дальней точки орбиты импульсом в перицентре'],['近地点点火','Periapsis burn','Импульс в перицентре'],['远端抬高','Far side rises','Дальний край поднимается'],['在轨道最低处沿飞行方向增加速度，会把轨道另一端抬得更高。','Adding speed along the direction of travel at the orbit’s lowest point raises the opposite side.','Увеличение скорости по ходу движения в нижней точке орбиты поднимает её противоположный край.'],['先观察黄色预测线的远端变化','Watch how the far end of the yellow prediction changes','Следите, как меняется дальний край жёлтого прогноза'],['决定点火时机，而不是照固定秒数','Choose when to burn instead of following a fixed duration','Выбирайте момент импульса, а не фиксированное число секунд'],
    ['同步轨道是什么','What is a synchronous orbit?','Что такое синхронная орбита?'],['卫星绕行周期匹配地球自转周期的示意图','Diagram of an orbital period matching Earth’s rotation period','Схема совпадения периода орбиты с периодом вращения Земли'],['飞船绕行','Spacecraft orbit','Полёт корабля'],['地球自转','Earth rotates','Земля вращается'],['同一周期','Same period','Одинаковый период'],['同步不是停下来，而是飞船绕地球一圈的时间与地球自转一圈相同。','Synchronous does not mean stopped; it means one orbit takes the same time as one Earth rotation.','Синхронность не означает остановку: один виток занимает столько же времени, сколько один оборот Земли.'],['轨道中的飞船仍在高速运动','The spacecraft is still moving quickly in orbit','Корабль на орбите всё ещё движется с большой скоростью'],['周期匹配后，从地面看位置才会保持不变','When the periods match, its position can appear fixed from the ground','Когда периоды совпадают, с Земли положение кажется неизменным'],['不再显示','Don’t show again','Больше не показывать'],['跳过','Skip','Пропустить'],
    ['星际快递员','Star Courier','Звёздный курьер'],['🚀 星际快递员','🚀 Star Courier','🚀 Звёздный курьер'],['轨道力学挑战','Orbital Mechanics Challenge','Испытание орбитальной механики'],['真实轨道力学 · 10 个航天任务','Real orbital mechanics · 10 space missions','Орбитальная механика · 10 миссий'],['星际快递员 · 轨道力学挑战','Star Courier · Orbital Mechanics Challenge','Звёздный курьер · Испытание орбитальной механики'],
    ['🚀 任务目录','🚀 Mission select','🚀 Выбор миссии'],['选择关卡 · 成绩保存在本设备','Choose a mission · Progress is saved on this device','Выберите миссию · Прогресс хранится на устройстве'],['最高分','Best score','Рекорд'],['开始任务','Start mission','Начать'],['开始最终任务','Start final mission','Начать финал'],['继续当前任务','Continue current mission','Продолжить миссию'],['飞船外观','Ship appearance','Внешний вид корабля'],['勋章收藏','Medal collection','Коллекция медалей'],
    ['⚙️ 航天器升级','⚙️ Spacecraft upgrades','⚙️ Улучшения корабля'],['关闭航天器升级','Close spacecraft upgrades','Закрыть улучшения корабля'],['首次通关 +1 点，挑战三星再 +1 点。','First completion: +1 point. First 3-star challenge: +1 more.','Первое прохождение: +1 очко. Первые 3 звезды в испытании: ещё +1.'],['可用升级点','Available upgrade points','Доступные очки улучшений'],['🔥 引擎效率','🔥 Engine efficiency','🔥 Эффективность двигателя'],['每级减少 4% 的推进燃料消耗。','Each level reduces propulsion fuel use by 4%.','Каждый уровень снижает расход топлива на тягу на 4%.'],['🛡️ 结构强化','🛡️ Structural reinforcement','🛡️ Усиление корпуса'],['每级提高 5% 的安全着陆容错速度。','Each level raises the safe landing speed tolerance by 5%.','Каждый уровень повышает допустимую скорость безопасной посадки на 5%.'],['升级 · 1 点','Upgrade · 1 point','Улучшить · 1 очко'],['已满级','Max level','Максимум'],['升级只在挑战模式生效；教学模式与示范飞船保持原参数。升级存档与关卡成绩独立保存。','Upgrades apply only in Challenge mode; Training and demo ships keep their original parameters. Upgrade data is saved separately from mission scores.','Улучшения действуют только в испытаниях; обучение и демонстрационные корабли сохраняют исходные параметры. Улучшения хранятся отдельно от результатов миссий.'],['升级完成，新的参数将在挑战模式立即生效。','Upgrade complete. The new parameters now apply in Challenge mode.','Улучшение завершено. Новые параметры действуют в режиме испытания.'],['该项目已满级。','This upgrade is already at max level.','Это улучшение уже максимального уровня.'],['升级点不足。','Not enough upgrade points.','Недостаточно очков улучшений.'],['点','pts','очк.'],['等级','Level','Уровень'],['燃料消耗','Fuel use','Расход топлива'],['着陆容错','Landing tolerance','Допуск посадки'],
    ['当前主导引力：','Dominant gravity: ','Главная гравитация: '],['多方拉扯','Multiple sources','Несколько источников'],['曙光星 A','Dawnstar A','Звезда Рассвета A'],['暮光星 B','Twilight Star B','Звезда Сумерек B'],['晨曦星','Dawnworld','Мир Рассвета'],['卡戎深渊','Charon Abyss','Бездна Харона'],['赫利俄斯 A','Helios A','Гелиос A'],['塞勒涅 B','Selene B','Селена B'],['厄瑞玻斯 C','Erebus C','Эреб C'],
    ['选择飞船外观','Choose a spacecraft','Выберите корабль'],['选择飞船与配套技能；关卡规则和无技能基础路线保持不变。','Choose a ship and its skill; mission rules and the skill-free baseline route stay unchanged.','Выберите корабль и его навык; правила миссий и базовый маршрут без навыков не меняются.'],['开发者模式','Developer mode','Режим разработчика'],['开发者测试','Developer test','Тест разработчика'],['🧪 开发者模式已开启：所有飞船可测试，不会写入正式解锁进度。','🧪 Developer mode is on: every ship is available for testing without changing normal unlock progress.','🧪 Режим разработчика включён: все корабли доступны для теста без изменения обычного прогресса.'],['经典火箭','Classic rocket','Классическая ракета'],['星际快递号','Star Courier','Звёздный курьер'],['皮实耐用，送货与着陆容错高。','Tough and dependable, with extra landing tolerance for deliveries.','Прочный и надёжный корабль с повышенным допуском при посадке грузов.'],['剑形飞行器','Sword-shaped craft','Корабль-меч'],['飞天一号','Feitian One','«Фэйтянь-1»'],['双长剑机首、五个圆形顶舱和白色紧凑机身。','Twin sword noses, five round domes and a compact white hull.','Два длинных носа-меча, пять круглых куполов и компактный белый корпус.'],['人族战列巡航舰','Terran battlecruiser','Терранский линейный крейсер'],['休伯利安号','Hyperion','«Гиперион»'],['横向重装舰首、细长中轴、双圆主翼与短促推进器尾段。','A transverse armoured bow, long central spine, twin circular main wings and a compact propulsion stern.','Поперечный бронированный нос, длинная центральная ось, два круглых крыла и короткая кормовая двигательная секция.'],['只改变外观，不改变碰撞判定、质量、推力、转向或关卡难度。选择会保存在这台设备上。','Appearance only: collision, mass, thrust, steering and difficulty stay unchanged. Saved on this device.','Меняется только вид: столкновения, масса, тяга, управление и сложность прежние. Выбор сохранится.'],
    ['🏅 飞行勋章收藏室','🏅 Flight medal cabinet','🏅 Коллекция лётных медалей'],['完成飞行壮举，填满属于你的勋章柜。','Complete flight feats and fill your medal cabinet.','Совершайте лётные подвиги и заполняйте коллекцию.'],['收好勋章','Close medal','Закрыть медаль'],['尚未解锁','Locked','Не открыто'],['已解锁','Unlocked','Открыто'],['解锁方法：','How to unlock: ','Как открыть: '],['解锁条件：','Requirement: ','Условие: '],
    ['地球同步卫星','Geostationary Satellite','Геостационарный спутник'],['载人航天返回','Crewed Return','Возвращение экипажа'],['空间站交会对接','Station Rendezvous','Стыковка со станцией'],['月背动力着陆','Lunar Far-side Landing','Посадка на обратной стороне'],['月球引力弹弓','Lunar Gravity Assist','Лунный гравитационный манёвр'],['地月引力平衡点','Earth–Moon Balance Points','Точки равновесия Земля–Луна'],['小行星拦截','Asteroid Intercept','Перехват астероида'],['双星摆渡','Binary-star Ferry','Переправа двойной системы'],['黑洞深渊点火','Black-hole Dive Burn','Импульс у чёрной дыры'],['三体 · 紧急救援','Three-body · Emergency Rescue','Три тела · Спасение'],
    ['把火箭飞进黄色同步轨道，再按按钮释放卫星。','Enter the yellow synchronous orbit, then release the satellite.','Выйдите на жёлтую синхронную орбиту и отделите спутник.'],['反向点火降回地球，打开降落伞并安全落地。','Burn retrograde, deploy the parachute and land safely.','Затормозите, раскройте парашют и мягко сядьте.'],['追上空间站，先把速度调成一样，再慢慢靠近对接。','Catch the station, match velocity, then approach slowly.','Догоните станцию, сравняйте скорость и медленно стыкуйтесь.'],['飞到月球背面，不用降落伞，只靠发动机安全落地。','Reach the lunar far side and land using engines only.','Долетите до обратной стороны Луны и сядьте только на двигателях.'],['借月球加速，飞出绿圈且不再返回。','Use the Moon to cross the green ring without falling back.','Разгонитесь у Луны и выйдите за зелёное кольцо без возврата.'],['任选一个地月引力平衡点，把卫星送到那里并停稳。','Choose any balance point, deliver the satellite and hold steady.','Выберите любую точку равновесия и удержите там спутник.'],['改变小行星轨道，让它避开地球和月球。','Deflect the asteroid away from Earth and Moon.','Уведите астероид от Земли и Луны.'],['穿过双星通道，与另一侧空间站对接。','Cross the binary corridor and dock on the far side.','Пройдите коридор двойной системы и состыкуйтесь.'],['在黑洞近点加速，再逃回绿色救援圈。','Burn near the black hole, then escape to the green rescue ring.','Разгонитесь у чёрной дыры и вернитесь к зелёному кольцу.'],['营救两艘失去动力的飞船，再带所有人逃离。','Rescue two powerless ships and escape with everyone.','Спасите два корабля и уйдите вместе.'],
    ['释放卫星','Release satellite','Отделить спутник'],['打开降落伞','Deploy parachute','Раскрыть парашют'],['执行对接','Dock','Стыковка'],['锚定并翻转','Anchor & flip','Якорь и переворот'],['解除锚定','Release anchor','Снять якорь'],['开启','On','Вкл.'],['关闭','Off','Выкл.'],['教学模式','Training mode','Обучение'],['挑战模式','Challenge mode','Испытание'],['有限燃料','Limited fuel','Топливо ограничено'],['无限燃料','Unlimited fuel','Топливо без лимита'],['燃料','Fuel','Топливо'],['生命维持','Life support','Жизнеобеспечение'],
    ['相对速度·地表','Relative speed · ground','Относительная скорость · поверхность'],['相对速度·月面','Relative speed · lunar surface','Относительная скорость · поверхность Луны'],['相对速度·月球','Relative speed · Moon','Относительная скорость · Луна'],['相对速度·空间站','Relative speed · station','Относительная скорость · станция'],['相对速度·目标点','Relative speed · target point','Относительная скорость · целевая точка'],['相对速度·小行星','Relative speed · asteroid','Относительная скорость · астероид'],['相对速度·暮光星','Relative speed · Twilight Star','Относительная скорость · звезда Сумерек'],['相对速度·暮光站','Relative speed · Twilight Station','Относительная скорость · станция Сумерек'],['相对速度·求救飞船','Relative speed · distress ship','Относительная скорость · аварийный корабль'],['相对速度·晨曦星地表','Relative speed · Dawnworld surface','Относительная скорость · поверхность Мира Рассвета'],
    ['高度','Altitude','Высота'],['速度','Speed','Скорость'],['距离','Distance','Расстояние'],['地球','Earth','Земля'],['月球','Moon','Луна'],['空间站','Station','Станция'],['目标','Target','Цель'],['完成','Complete','Готово'],['任务失败','Mission failed','Миссия провалена'],['任务成功','Mission complete','Миссия выполнена'],
    ['自动旋转','Auto rotate','Автоповорот'],['横屏驾驶','Landscape','Альбомный режим'],['竖屏驾驶','Portrait','Портретный режим'],['建议横屏游玩','Landscape recommended','Рекомендуется альбомный режим'],['建议竖屏游玩','Portrait recommended','Рекомендуется портретный режим'],['请转动设备以使用所选布局','Rotate the device to use this layout','Поверните устройство для выбранного режима'],['浏览器未允许自动旋转，请手动转动设备','Auto rotation was blocked; rotate the device manually','Автоповорот заблокирован; поверните устройство вручную'],
    ['随速偏转','Velocity assist','По скорости'],['手动转向','Manual steering','Ручное управление'],['纯惯性','Inertial steering','Инерционное управление'],['轨道','Orbit','Орбита'],['全局','Global','Общая'],['任务导航正常','Navigation nominal','Навигация в норме'],['暂停菜单可隐藏指引','Guidance can be hidden in Pause','Подсказки можно скрыть в паузе'],['查看简报拿三星','See briefing for three stars','Условия трёх звёзд — в брифинге'],['完成得 1 星','Complete for 1 star','За выполнение — 1 звезда'],['按住推进','Hold thrust','Удерживайте тягу'],['阶段完成','Stage complete','Этап завершён'],
    ['这枚勋章现在还是空的。先给它一个值得吐槽的故事。','This medal is still empty. Give it a story worth teasing.','Эта медаль пока пуста. Подарите ей историю, достойную шутки.'],['点击查看勋章吐槽','Open for the medal comment','Открыть комментарий к медали'],['点击勋章查看收藏吐槽','Tap a medal to read its comment','Нажмите медаль, чтобы прочитать комментарий'],['尚未解锁','Locked','Не открыто'],['未解锁','Locked','Не открыто']
    ,['下一步','NEXT','ДАЛЕЕ'],['再玩一次 (R)','Play again (R)','Ещё раз (R)'],['下一关 (L)','Next mission (L)','Следующая миссия (L)'],['任务目录','Mission select','Выбор миссии'],['登陆成功！','Landing complete!','Посадка выполнена!'],['月球运动方向','Moon direction','Движение Луны'],['地球、月球和L1至L5位置示意图','Earth, Moon and L1–L5 diagram','Схема Земли, Луны и L1–L5'],['关闭科普页面','Close science page','Закрыть страницу науки'],['关闭飞船外观','Close spacecraft picker','Закрыть выбор корабля'],['关闭勋章收藏','Close medal collection','Закрыть коллекцию'],['关闭暂停菜单并继续飞行','Close pause menu and resume','Закрыть паузу и продолжить'],['切换视角模式','Change camera mode','Сменить камеру'],['暂停游戏','Pause game','Пауза'],['按住八倍速','Hold for 8× speed','Удерживать для скорости 8×'],['向左转向','Turn left','Поворот влево'],['向右转向','Turn right','Поворот вправо'],['执行任务动作','Mission action','Действие миссии'],
    ['把火箭飞进绿色同步轨道，再按按钮释放卫星。','Enter the green synchronous orbit, then release the satellite.','Выйдите на зелёную синхронную орбиту и отделите спутник.'],
    ['🚀 开始航天执照','🚀 Start your spaceflight license','🚀 Начать лётную лицензию'],['推荐任务','Recommended mission','Рекомендуемая миссия'],['推荐路径','Recommended path','Рекомендуемый путь'],['自由任务','Free missions','Свободные миссии'],['全部任务始终可玩','Every mission is always playable','Все миссии всегда доступны'],['已完成任务与下一项训练','Completed missions and your next exercise','Выполненные миссии и следующее упражнение'],
    ['第一幕 · 地球轨道执照','Act I · Earth Orbit License','Акт I · Лицензия земной орбиты'],['第二幕 · 地月航路','Act II · Earth–Moon Route','Акт II · Трасса Земля–Луна'],['第三幕 · 深空危机','Act III · Deep-space Crisis','Акт III · Кризис в дальнем космосе'],['第四幕 · 极端宇宙','Act IV · Extreme Universe','Акт IV · Экстремальная вселенная'],
    ['📖 战役日志','📖 Campaign log','📖 Журнал кампании'],['关闭战役日志','Close campaign log','Закрыть журнал кампании'],['CAMPAIGN ARCHIVE','CAMPAIGN ARCHIVE','АРХИВ КАМПАНИИ'],['完成一幕后，可在这里回看任务成绩与航程记录。','Complete an act to review its mission results and flight record here.','Завершите акт, чтобы просмотреть результаты миссий и журнал полёта.'],
    ['战役总结','Campaign summary','Итоги кампании'],['战役完成','Campaign complete','Кампания завершена'],['四幕航程已经全部完成。','All four acts of the voyage are complete.','Все четыре акта путешествия завершены.'],['本幕任务全部完成，以下是你的实际航程记录。','Every mission in this act is complete. Here is your actual flight record.','Все миссии акта завершены. Вот ваша фактическая запись полёта.'],['已记录','Recorded','Записано'],['完成本幕后解锁','Complete this act to unlock','Завершите акт для доступа'],['点击任意处继续','Click anywhere to continue','Нажмите в любом месте, чтобы продолжить'],
    ['把同步卫星稳定送入任务轨道','Placed the synchronous satellite into its mission orbit','Стабильно вывели синхронный спутник на рабочую орбиту'],['将乘员安全带回地面','Brought the crew safely back to the surface','Безопасно вернули экипаж на поверхность'],['向空间站完成补给对接','Completed the station supply docking','Выполнили снабжение и стыковку со станцией'],['把科考队送达月球背面','Delivered the research team to the lunar far side','Доставили исследователей на обратную сторону Луны'],['借用月球引力飞出地球','Used lunar gravity to escape Earth','Использовали гравитацию Луны для ухода от Земли'],['在地月平衡区部署中继','Deployed a relay in an Earth–Moon balance zone','Развернули ретранслятор в зоне равновесия Земля–Луна'],['改变小行星航向守住家园','Deflected the asteroid and protected home','Изменили курс астероида и защитили дом'],['穿越双星并补给暮光站','Crossed the binary system and supplied Twilight Station','Прошли двойную систему и снабдили станцию «Сумерки»'],['从黑洞深渊带回乘员','Returned the crew from the black-hole abyss','Вернули экипаж из бездны чёрной дыры'],['营救求救飞船并逃离三体系统','Rescued the distress ships and escaped the three-body system','Спасли аварийные корабли и покинули систему трёх тел'],
    ['你已取得地球轨道执照，任务范围将越过近地空间。','You have earned your Earth-orbit license. The next missions go beyond near-Earth space.','Вы получили лицензию земной орбиты. Следующие миссии выходят за пределы околоземного пространства.'],['地月航路已经贯通，下一次警报来自更远的深空。','The Earth–Moon route is open. The next alert comes from deeper space.','Трасса Земля–Луна открыта. Следующий сигнал тревоги идёт из дальнего космоса.'],['你在深空危机中证明了应变能力，极端宇宙正在等待。','You proved yourself in a deep-space crisis. Extreme space is waiting.','Вы доказали себя в кризисе дальнего космоса. Впереди — экстремальная вселенная.'],['十项任务全部完成：你已从轨道学员成长为星际航行员。','All ten missions are complete: you have grown from orbital trainee to interstellar pilot.','Все десять миссий завершены: из орбитального курсанта вы стали межзвёздным пилотом.'],
    ['下一幕预告 · 地月航路','Next act · Earth–Moon Route','Следующий акт · Трасса Земля–Луна'],['下一幕预告 · 深空危机','Next act · Deep-space Crisis','Следующий акт · Кризис в дальнем космосе'],['下一幕预告 · 极端宇宙','Next act · Extreme Universe','Следующий акт · Экстремальная вселенная'],['战役完成 · 航程记录已归档','Campaign complete · Flight record archived','Кампания завершена · Журнал полёта сохранён'],
    ['推荐路径 · 第一幕 · 地球轨道执照','Recommended path · Act I · Earth Orbit License','Рекомендуемый путь · Акт I · Лицензия земной орбиты'],['推荐路径 · 第二幕 · 地月航路','Recommended path · Act II · Earth–Moon Route','Рекомендуемый путь · Акт II · Трасса Земля–Луна'],['推荐路径 · 第三幕 · 深空危机','Recommended path · Act III · Deep-space Crisis','Рекомендуемый путь · Акт III · Кризис в дальнем космосе'],['推荐路径 · 第四幕 · 极端宇宙','Recommended path · Act IV · Extreme Universe','Рекомендуемый путь · Акт IV · Экстремальная вселенная'],
    ['📡 执照回响：','📡 License echo: ','📡 Эхо лицензии: '],['第一关技能：稳定绕行','Mission 1 skill: stable orbit','Навык миссии 1: устойчивая орбита'],['第一关技能：近地点顺向点火','Mission 1 skill: prograde burn at periapsis','Навык миссии 1: разгон в перицентре'],['第二关技能：控制接地速度','Mission 2 skill: control touchdown speed','Навык миссии 2: контроль скорости касания'],['第四关技能：相对月球减速捕获','Mission 4 skill: slow relative to the Moon for capture','Навык миссии 4: торможение относительно Луны для захвата'],['第三关技能：先消速度差再对接','Mission 3 skill: cancel Relative speed · station before docking','Навык миссии 3: снизить «Относительная скорость · станция» перед стыковкой'],['第一关技能：在最近点顺向点火','Mission 1 skill: burn prograde at closest approach','Навык миссии 1: разгон в ближайшей точке'],['第三关技能：相对速度匹配','Mission 3 skill: match Relative speed · distress ship','Навык миссии 3: согласовать «Относительная скорость · аварийный корабль»'],
    ['🧭 信息层级','🧭 Information layers','🧭 Слои информации'],['关闭暂时不需要的信息；危险警告仍会保留。','Hide information you do not need; danger alerts remain visible.','Скрывайте лишнюю информацию; опасные предупреждения останутся.'],['遥测','Telemetry','Телеметрия'],['G / 引力','G / Gravity','G / Гравитация'],['阶段提示','Stage guidance','Подсказки этапа'],['目标标记','Target markers','Метки целей'],['显示','Show','Показать'],['隐藏','Hide','Скрыть'],['术语 ?','Terms ?','Термины ?'],['航天术语解释','Spaceflight term explanations','Объяснение терминов космонавтики'],['相对速度·参照物','Relative speed · reference','Относительная скорость · ориентир'],
    ['轨道上离当前中心天体最远的位置。在近地点顺向点火，通常会把远地点抬高。','The point in an orbit farthest from the current central body. A prograde burn at periapsis usually raises it.','Самая дальняя от текущего центрального тела точка орбиты. Разгон в перицентре обычно поднимает её.'],
    ['飞船速度减去参照物运动后的速度。着陆、对接时应看对应参照物，而不是只看绝对速度。','Ship velocity after subtracting the reference object’s motion. For landing or docking, use the relevant reference instead of absolute speed.','Скорость корабля после вычитания движения ориентира. При посадке и стыковке важен нужный ориентир, а не абсолютная скорость.'],
    ['预计飞到无限远后仍剩下的速度。大于 0 表示已获得不会掉回地球的逃逸能量。','The speed predicted to remain infinitely far away. Above 0 means enough escape energy to avoid falling back to Earth.','Расчётная скорость на бесконечном удалении. Значение выше 0 означает достаточную энергию, чтобы не упасть обратно на Землю.'],
    ['最终考核 · 本次任务将调用你全部的训练','Final assessment · This mission will call on all your training','Итоговый экзамен · В этой миссии пригодится вся ваша подготовка'],
    ['最终考核','Final assessment','Итоговый экзамен'],['营救','Rescued','Спасено'],['点击展开','Click to expand','Нажмите, чтобы раскрыть'],['点击收起','Click to collapse','Нажмите, чтобы свернуть'],
    ['交会接近','Rendezvous approach','Сближение'],['船员转移','Crew transfer','Эвакуация экипажа'],['危险规避','Hazard avoidance','Обход опасности'],['成功逃逸','Successful escape','Успешный уход'],
    ['已达成','Complete','Выполнено'],['待完成','Pending','Ожидает'],['待结算','Evaluated at finish','Оценка в конце'],['未达成','Not achieved','Не выполнено'],
    ['🧭 航程奖励方向','🧭 Reward flight plan','🧭 Маршрут наград'],['星星推进战役 · 勋章邀请特殊玩法 · 分数用于高手优化 · 外观记录成长','Stars advance the campaign · medals invite special play · scores reward expert optimization · skins record growth','Звёзды двигают кампанию · медали предлагают особые стили · очки нужны мастерам · облики отмечают рост'],
    ['战役星星','Campaign stars','Звёзды кампании'],['下一外观','Next skin','Следующий облик'],['特殊勋章','Special medals','Особые медали'],['高手纪录','Expert records','Рекорды мастера'],['不同路线与驾驶限制','Different routes and flight constraints','Другие маршруты и ограничения'],['不作为普通通关门槛','Never required for normal completion','Не требуется для обычного прохождения'],['燃料与时间只在这里拉开差距','Fuel and time separate expert scores here','Топливо и время различают рекорды здесь'],
    ['星','stars','звёзд'],['幕已完成','acts complete','актов завершено'],['再获得','Earn','Получите ещё'],['星解锁飞天一号','more stars to unlock Feitian One','звёзд, чтобы открыть «Фэйтянь-1»'],['飞天一号已达到星级条件','Feitian One star requirement met','Условие звёзд для «Фэйтянь-1» выполнено'],['十关最高分合计','Total best score across ten missions','Сумма рекордов десяти миссий'],['外观已解锁','skins unlocked','обликов открыто'],
    ['勋章邀请你尝试不同路线与驾驶限制，不作为普通通关门槛。','Medals invite different routes and flight constraints; they are never required for normal completion.','Медали предлагают другие маршруты и ограничения, но не нужны для обычного прохождения.'],['勋章邀请你尝试不同路线与驾驶限制','Medals invite different routes and flight constraints','Медали предлагают другие маршруты и ограничения'],
    ['累计获得 12 星解锁','Unlock at 12 total stars','Открывается за 12 звёзд'],['获得“挑战王牌”勋章解锁','Unlock with the “Challenge Ace” medal','Открывается медалью «Ас испытаний»'],['✓ 已解锁','✓ Unlocked','✓ Открыто'],['默认解锁','Unlocked by default','Открыто по умолчанию'],['尚未解锁：','Locked: ','Не открыто: '],
    ['外观由战役星星或特殊勋章解锁；只改变外观，不改变碰撞判定、质量、推力、转向或关卡难度。旧版本已经选用的外观会保留。','Skins unlock through campaign stars or special medals. They change appearance only, never collision, mass, thrust, steering or difficulty. Previously selected skins stay owned.','Облики открываются звёздами кампании или особыми медалями. Они не меняют столкновения, массу, тягу, управление или сложность. Ранее выбранные облики сохраняются.'],
    ['点火段不超过 6 次：+★','No more than 6 burn segments: +★','Не более 6 импульсов: +★'],['点火段不超过 6 次','No more than 6 burn segments','Не более 6 импульсов'],['无阶段回退完成：+★','Finish without stage rewind: +★','Без отката этапа: +★'],['无阶段回退完成','Finish without stage rewind','Без отката этапа'],['单次无动力滑行至少 25 秒：+★','Coast unpowered for at least 25 seconds: +★','Полёт без тяги не менее 25 секунд: +★'],['单次无动力滑行至少 25 秒','Coast unpowered for at least 25 seconds','Полёт без тяги не менее 25 секунд'],['单次无动力滑行至少 20 秒：+★','Coast unpowered for at least 20 seconds: +★','Полёт без тяги не менее 20 секунд: +★'],['单次无动力滑行至少 20 秒','Coast unpowered for at least 20 seconds','Полёт без тяги не менее 20 секунд'],['点火段不超过 8 次：+★','No more than 8 burn segments: +★','Не более 8 импульсов: +★'],['点火段不超过 8 次','No more than 8 burn segments','Не более 8 импульсов'],['点火段不超过 3 次：+★','No more than 3 burn segments: +★','Не более 3 импульсов: +★'],['点火段不超过 3 次','No more than 3 burn segments','Не более 3 импульсов'],['营救求救飞船并逃离三体系统：★','Rescue the distress ships and escape the three-body system: ★','Спасите аварийные корабли и покиньте систему трёх тел: ★'],
    ['S 级纪录','S-rank record','Рекорд S'],['A 级 · 距 S 级','A rank · to S rank','Ранг A · до S'],['B 级 · 距 A 级','B rank · to A rank','Ранг B · до A'],['C 级 · 距 B 级','C rank · to B rank','Ранг C · до B'],['尚无纪录','No record yet','Рекорда пока нет'],['分','points','очков'],
    ['飞船技能','Spacecraft skill','Навык корабля'],['技能','Skill','Навык'],['就绪','Ready','Готово'],['已用','Spent','Использовано'],['已使用','Used','Использован'],['未使用','Unused','Не использован'],['生效中','Active','Активен'],['被动','Passive','Пассивный'],['每关一次','Once per mission','Один раз за миссию'],['待安装','Coming next','Будет установлено'],['已碎裂','Broken','Разрушен'],['使用技能','Use skill','Использовать навык'],
    ['技能尚未安装','This skill is not installed yet','Этот навык ещё не установлен'],['被动技能会自动生效','Passive skills activate automatically','Пассивные навыки срабатывают автоматически'],['本关技能已使用','The skill has already been used this mission','Навык уже использован в этой миссии'],['本关技能次数已用完','No skill charges remain this mission','В этой миссии заряды навыка закончились'],['技能冷却中','Skill is cooling down','Навык перезаряжается'],['冷却','Cooldown','Перезарядка'],['燃料不足，无法折跃','Not enough fuel to warp','Недостаточно топлива для скачка'],['被动技能自动生效','Passive skill activates automatically','Пассивный навык срабатывает автоматически'],['按 F 或技能按钮使用 · 每关一次','Press F or the skill button · once per mission','Нажмите F или кнопку навыка · один раз за миссию'],['按 F 或技能按钮使用 · 每关三次','Press F or the skill button · three times per mission','Нажмите F или кнопку навыка · три раза за миссию'],['每关三次','Three per mission','Трижды за миссию'],
    ['缓冲货叉','Cushion Fork','Амортизирующая вилка'],['安全着陆速度上限提高 15%。','Raises the safe touchdown speed limit by 15%.','Повышает предел скорости безопасной посадки на 15%.'],['擅长：返回与着陆任务','Best for: return and landing missions','Лучше всего: возвращение и посадка'],
    ['空间折跃','Space Warp','Пространственный скачок'],['按住聚能 0.1 秒后沿机头折跃 150u，松手取消；每关 3 次，挑战模式每次消耗 5% 燃料，冷却 5 秒。','Hold for a 0.1-second charge, then warp 150u along the nose; release to cancel. Three uses per mission, each costing 5% fuel in Challenge mode with a 5-second cooldown.','Удерживайте 0,1 с, затем совершите скачок на 150u по курсу носа; отпустите для отмены. Три раза за миссию, расход 5% топлива в испытании и перезарядка 5 секунд.'],['擅长：连续交会与路径修正','Best for: repeated rendezvous and course corrections','Лучше всего: повторные сближения и коррекции курса'],
    ['空间折跃完成','Space warp complete','Пространственный скачок завершён'],['空间折跃聚能 · 按住 0.1 秒','Space Warp charging · hold for 0.1 seconds','Зарядка пространственного скачка · удерживайте 0,1 с'],['已取消空间折跃聚能','Space Warp charge cancelled','Зарядка пространственного скачка отменена'],['折跃聚能','Warp charge','Зарядка скачка'],['技能正在聚能','Skill is charging','Навык заряжается'],['折跃路径被天体安全截断','Warp path safely clipped by a celestial body','Путь скачка безопасно обрезан небесным телом'],['折跃抵达世界边界','Warp stopped at the world boundary','Скачок остановлен у границы мира'],['飞船状态不允许折跃','The spacecraft cannot warp in its current state','Корабль не может совершить скачок в текущем состоянии'],
    ['大和炮','Yamato Cannon','Пушка «Ямато»'],['按住聚能 0.9 秒后发射，松手取消；命中小行星会将其击碎，命中友方空间站会导致任务失败。','Hold to charge for 0.9 seconds and fire; release to cancel. Asteroid hits shatter the target, while hitting a friendly station fails the mission.','Удерживайте 0,9 с для зарядки и выстрела; отпустите для отмены. Попадание разбивает астероид, а уничтожение дружественной станции проваливает миссию.'],['擅长：小行星防御 · 每关一次','Best for: asteroid defence · once per mission','Лучше всего: защита от астероидов · один раз за миссию'],
    ['飞船状态不允许开炮','The spacecraft cannot fire in its current state','Корабль не может стрелять в текущем состоянии'],['大和炮开始聚能 · 按住并保持瞄准','Yamato Cannon charging · hold and keep aiming','Пушка «Ямато» заряжается · удерживайте кнопку и прицел'],['已取消大和炮聚能','Yamato Cannon charge cancelled','Зарядка пушки «Ямато» отменена'],['按住使用技能','Hold to use skill','Удерживайте для навыка'],['按住 F 或技能按钮聚能 · 松开取消','Hold F or the skill button to charge · release to cancel','Удерживайте F или кнопку навыка для зарядки · отпустите для отмены'],['聚能','Charging','Зарядка'],['发射中','Firing','Огонь'],['大和炮击碎小行星','Yamato Cannon shattered the asteroid','Пушка «Ямато» разбила астероид'],['大和炮击毁友方空间站','Yamato Cannon destroyed the friendly station','Пушка «Ямато» уничтожила дружественную станцию'],['块','fragments','фрагментов'],['大和炮命中小行星','Yamato Cannon hit the asteroid','Пушка «Ямато» попала в астероид'],['光束消散在','The beam dissipated in','Луч рассеялся в'],['引力场中','gravity field','гравитационном поле'],['大和炮射程内没有目标','No target within Yamato Cannon range','В радиусе пушки «Ямато» нет цели'],['大和炮定向冲量','Yamato directional impulse','Направленный импульс «Ямато»'],['空间站','space station','космическая станция'],['求救飞船 A','distress ship A','аварийный корабль A'],['求救飞船 B','distress ship B','аварийный корабль B'],
    ['飞船由战役星星或特殊勋章解锁；技能提供不同操作工具，但不改变任务成功判定、星级条件或无技能基础通关路线。旧版本已经选用的外观会保留。','Ships unlock through campaign stars or special medals. Skills provide different tools, but never change mission success rules, star conditions, or the skill-free baseline route. Previously selected skins stay owned.','Корабли открываются звёздами кампании или особыми медалями. Навыки дают разные инструменты, но не меняют условия успеха, звёзд или базовый маршрут без навыков. Ранее выбранные облики сохраняются.'],
    ['白色装甲、青色座舱与红色短翼的轻型快递船。','A light courier with white armour, a cyan canopy and short red wings.','Лёгкий курьер с белой бронёй, голубым фонарём и короткими красными крыльями.'],
    ['白色装甲、青色座舱与红色短翼；皮实耐用，送货与着陆容错高。','White armour, a cyan canopy and short red wings; tough and dependable, with extra landing tolerance for deliveries.','Белая броня, голубой фонарь и короткие красные крылья; прочный курьер с повышенным допуском при посадке грузов.']
  ];

  const missionContent=global.SpaceGameMissionContent||null;
  const achievementContent=global.SpaceGameAchievementContent||null;
  const baseMission=missionContent?JSON.parse(JSON.stringify(missionContent)):null;
  const baseAchievements=achievementContent?JSON.parse(JSON.stringify(achievementContent)):null;
  const exact={en:new Map(),ru:new Map()};
  const addRow=(zh,en,ru)=>{if(zh){exact.en.set(zh,en);exact.ru.set(zh,ru);}};
  UI_ROWS.forEach(row=>addRow(...row));
  if(baseMission){
    for(let i=1;i<=10;i++){
      const z=baseMission.levels[i],e=EN.levels[i-1],r=RU.levels[i-1];[z.title,z.sub,z.brief].forEach((s,j)=>addRow(s,e[j],r[j]));
      baseMission.stages[i].forEach((stage,j)=>{const rows=[stage.name,stage.hint,...stage.steps,stage.success],es=EN.stages[i-1][j],rs=RU.stages[i-1][j];rows.forEach((s,k)=>addRow(s,es[k],rs[k]));});
      const zs=baseMission.science[i],es=EN.science[i-1],rs=RU.science[i-1];addRow(zs.title,es[0],rs[0]);addRow(zs.intro,es[1],rs[1]);zs.sections.forEach((section,j)=>{addRow(section.title,es[2][j][0],rs[2][j][0]);addRow(section.text,es[2][j][1],rs[2][j][1]);});
    }
  }
  if(baseAchievements){baseAchievements.forEach((item,i)=>{const e=ACH_TRANSLATIONS.en[i],r=ACH_TRANSLATIONS.ru[i];addRow(item.title,e[0],r[0]);addRow(item.method,e[1],r[1]);addRow(item.joke,e[2],r[2]);});}

  const PARTS=[
    ['色觉辅助：','Color vision assist: ','Помощь цветовосприятия: '],
    ['预测区域宽度','Prediction region width','Ширина области прогноза'],
    ['相对速度·晨曦星地表','Relative speed · Dawnworld surface','Относительная скорость · поверхность Мира Рассвета'],
    ['相对速度·暮光站','Relative speed · Twilight Station','Относительная скорость · станция Сумерек'],
    ['相对速度·求救飞船','Relative speed · distress ship','Относительная скорость · аварийный корабль'],
    ['相对速度·空间站','Relative speed · station','Относительная скорость · станция'],
    ['相对速度·目标点','Relative speed · target point','Относительная скорость · целевая точка'],
    ['相对速度·小行星','Relative speed · asteroid','Относительная скорость · астероид'],
    ['相对速度·暮光星','Relative speed · Twilight Star','Относительная скорость · звезда Сумерек'],
    ['相对速度·月面','Relative speed · lunar surface','Относительная скорость · поверхность Луны'],
    ['相对速度·月球','Relative speed · Moon','Относительная скорость · Луна'],
    ['相对速度·地表','Relative speed · ground','Относительная скорость · поверхность'],
    ['当前主导引力：','Dominant gravity: ','Главная гравитация: '],['多方拉扯','Multiple sources','Несколько источников'],
    ['曙光星 A','Dawnstar A','Звезда Рассвета A'],['暮光星 B','Twilight Star B','Звезда Сумерек B'],['晨曦星','Dawnworld','Мир Рассвета'],['卡戎深渊','Charon Abyss','Бездна Харона'],
    ['赫利俄斯 A','Helios A','Гелиос A'],['塞勒涅 B','Selene B','Селена B'],['厄瑞玻斯 C','Erebus C','Эреб C'],
    ['固定本局：整关重来保持当前宇宙。','Lock current: a full restart keeps this universe.','Фиксация: полный перезапуск сохраняет эту вселенную.'],
    ['随机：下次整关重来生成新宇宙；阶段回退保留本局。','Random: the next full restart creates a new universe; stage rewind keeps this run.','Случайно: полный перезапуск создаёт новую вселенную; откат этапа сохраняет текущую.'],
    ['地球逃逸门','Earth escape gate','Ворота ухода от Земли'],
    ['轨迹预测：','Trajectory: ','Траектория: '],['小地图：','Radar: ','Карта: '],['姿态：','Attitude: ','Ориентация: '],['表盘：','Dial: ','Прибор: '],['新手指引：','Guidance: ','Подсказки: '],['屏幕方向：','Screen: ','Экран: '],['音效：','Sound: ','Звук: '],['音乐：','Music: ','Музыка: '],['模式：','Mode: ','Режим: '],['宇宙种子：','Universe seed: ','Семя вселенной: '],['📋 复制种子 ','📋 Copy seed ','📋 Копировать семя '],['✅ 种子已复制：','✅ Seed copied: ','✅ Семя скопировано: '],['🔒 已固定本局种子 ','🔒 Locked current seed ','🔒 Зафиксировано текущее семя '],['当前种子 ','Current seed ','Текущее семя '],['任务 ','Mission ','Миссия '],['已解锁 ','Unlocked ','Открыто '],['首次达成奖励：','First-time reward: ','Награда за первое достижение: '],['升级：','Upgrades: ','Улучшения: '],['升级点','upgrade points','очков улучшений'],['燃料消耗','Fuel use','Расход топлива'],['着陆容错','Landing tolerance','Допуск посадки'],['距目标','To target','До цели'],['距月球','To Moon','До Луны'],['距月','To Moon','До Луны'],['预计碰撞','Predicted impact','Прогноз столкновения'],['逃逸余速','Escape speed','Скорость ухода'],['逃逸能量','Escape energy','Энергия ухода'],['近地点','Periapsis','Перицентр'],['远地点','Apoapsis','Апоцентр'],['预计近月点','Predicted lunar periapsis','Перицентр у Луны'],['世界固定','World-up','Мир сверху'],['速度向上','Velocity-up','Скорость вверх'],['机头向上','Nose-up','Нос вверх'],['全局地图','Global map','Общая карта'],['局部地图','Local map','Локальная карта'],['同步带','Sync band','Синхронная зона'],['着陆区','Landing zone','Зона посадки'],['月球借力','Lunar assist','Манёвр у Луны'],['地球逃逸门','Earth escape gate','Ворота ухода от Зем球'],['目标小行星','Target asteroid','Целевой астероид'],['安全边界','Safe boundary','Граница безопасности'],['引力通道','Gravity corridor','Гравитационный коридор'],['暮光站','Twilight Station','Станция «Сумерки»'],['黑洞近点','Black-hole periapsis','Перицентр чёрной дыры'],['远方救援门','Rescue gate','Спасательные ворота'],['最近：','Nearest: ','Ближайший: '],['最近求救','Nearest distress','Ближайший сигнал'],['求救飞船','distress ship','корабль бедствия'],['开启','On','Вкл.'],['关闭','Off','Выкл.'],['飞行时间','Flight time','Время полёта'],['剩余燃料','Fuel remaining','Остаток топлива'],['得分','Score','Счёт'],['绝对速度','Absolute speed','Абсолютная скорость'],['轨道速度','Orbital speed','Орбитальная скорость'],['相对地面','Ground relative','Относительно поверхности'],['空间站距离','Station distance','До станции'],['距小行星','To asteroid','До астероида'],['相对目标','Target relative','Относительно цели'],['同步带高度','Sync altitude','Высота синхронной зоны'],['目标：','Target: ','Цель: '],['预测：','Forecast: ','Прогноз: '],['燃料剩余至少','Fuel remaining at least','Остаток топлива не менее'],['时间','Time','Время'],['分','pts','очк.'],['星','star','звезда'],['秒','s','с']
  ];
  let locale=(()=>{try{const value=localStorage.getItem(KEY);return SUPPORTED.includes(value)?value:'zh';}catch(_){return'zh';}})();
  function trText(value){
    if(locale==='zh'||typeof value!=='string'||!value)return value;
    const direct=exact[locale].get(value);if(direct!==undefined)return direct;
    const leading=value.match(/^\s*/)?.[0]||'',trailing=value.match(/\s*$/)?.[0]||'',core=value.slice(leading.length,value.length-trailing.length);
    const trimmed=exact[locale].get(core);if(trimmed!==undefined)return leading+trimmed+trailing;
    let out=value;for(const row of PARTS){out=out.split(row[0]).join(locale==='en'?row[1]:row[2]);}
    return out;
  }
  function copyLevel(target,row){target.title=row[0];target.sub=row[1];target.brief=row[2];}
  function copyStage(target,row){target.name=row[0];target.hint=row[1];target.steps=[row[2],row[3]];target.success=row[4];}
  function copyScience(target,row){target.title=row[0];target.intro=row[1];target.sections.forEach((section,j)=>{section.title=row[2][j][0];section.text=row[2][j][1];});}
  function applyStructuredData(){
    if(baseMission&&missionContent){for(let i=1;i<=10;i++){const pack=locale==='zh'?null:(locale==='en'?EN:RU);if(pack){copyLevel(missionContent.levels[i],pack.levels[i-1]);missionContent.stages[i].forEach((stage,j)=>copyStage(stage,pack.stages[i-1][j]));copyScience(missionContent.science[i],pack.science[i-1]);}else{copyLevel(missionContent.levels[i],[baseMission.levels[i].title,baseMission.levels[i].sub,baseMission.levels[i].brief]);missionContent.stages[i].forEach((stage,j)=>copyStage(stage,[baseMission.stages[i][j].name,baseMission.stages[i][j].hint,...baseMission.stages[i][j].steps,baseMission.stages[i][j].success]));copyScience(missionContent.science[i],[baseMission.science[i].title,baseMission.science[i].intro,baseMission.science[i].sections.map(s=>[s.title,s.text])]);}}}
    if(baseAchievements&&achievementContent){achievementContent.forEach((item,i)=>{if(locale==='zh'){item.title=baseAchievements[i].title;item.method=baseAchievements[i].method;item.joke=baseAchievements[i].joke;}else{const row=ACH_TRANSLATIONS[locale][i];item.title=row[0];item.method=row[1];item.joke=row[2];}});}
  }

  const textSources=new WeakMap(),attrSources=new WeakMap(),ATTRS=['aria-label','title','placeholder','alt'];
  const hasHan=text=>/[\u3400-\u9fff]/.test(text||'');
  function translateTextNode(node){
    const current=node.nodeValue||'';let source=textSources.get(node);
    if(source===undefined||hasHan(current)){source=current;textSources.set(node,source);}
    const expected=trText(source);if(current!==expected)node.nodeValue=expected;
  }
  function translateElement(el){
    let sources=attrSources.get(el);if(!sources){sources={};attrSources.set(el,sources);}
    for(const attr of ATTRS){if(!el.hasAttribute?.(attr))continue;const current=el.getAttribute(attr);if(sources[attr]===undefined||hasHan(current))sources[attr]=current;const expected=trText(sources[attr]);if(current!==expected)el.setAttribute(attr,expected);}
  }
  function translateDOM(root=document){
    if(!root||typeof document==='undefined')return;
    if(root.nodeType===3){translateTextNode(root);return;}
    if(root.nodeType===1)translateElement(root);
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,{acceptNode(node){const tag=node.parentElement?.tagName;return tag==='SCRIPT'||tag==='STYLE'?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT;}});
    let node;while((node=walker.nextNode())){if(node.nodeType===3)translateTextNode(node);else translateElement(node);}
  }
  function patchCanvas(){
    const proto=global.CanvasRenderingContext2D?.prototype;if(!proto||proto.__spacegameI18n)return;
    for(const name of ['fillText','strokeText','measureText']){const original=proto[name];if(typeof original!=='function')continue;proto[name]=function(text,...args){return original.call(this,trText(String(text)),...args);};}
    proto.__spacegameI18n=true;
  }
  function buttonText(){return `🌐 ${LABELS[locale]}`;}
  function refresh(){applyStructuredData();if(typeof document!=='undefined'){document.documentElement.lang=locale==='zh'?'zh-CN':locale;document.documentElement.style.setProperty('--next-step-label',`'${locale==='zh'?'下一步':locale==='en'?'NEXT':'ДАЛЕЕ'}'`);translateDOM(document);for(const id of ['menuLanguage','menuLanguageHome']){const button=document.getElementById(id);if(button)button.textContent=buttonText();}}}
  function set(next,{silent=false}={}){if(!SUPPORTED.includes(next))next='zh';locale=next;try{localStorage.setItem(KEY,locale);}catch(_){}refresh();if(!silent&&typeof dispatchEvent==='function')dispatchEvent(new CustomEvent('spacegame-languagechange',{detail:{locale}}));return status();}
  function cycle(){const index=SUPPORTED.indexOf(locale);return set(SUPPORTED[(index+1)%SUPPORTED.length]);}
  function status(){return{locale,label:LABELS[locale],button:buttonText()};}
  patchCanvas();applyStructuredData();
  if(typeof document!=='undefined'){
    refresh();
    const observer=new MutationObserver(records=>{for(const record of records){if(record.type==='characterData')translateTextNode(record.target);else{record.addedNodes.forEach(node=>translateDOM(node));if(record.type==='attributes')translateElement(record.target);}}});
    observer.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:ATTRS});
  }
  global.SpaceGameI18n={t:trText,set,cycle,status,refresh,supported:()=>SUPPORTED.slice()};
  global.cycleLanguage=cycle;
})(globalThis);
